language: go

go:
- "1.10"
- 1.11
- 1.12

notifications:
  email:
    recipients: quinn@quinncasey.com
    on_success: change
    on_failure: always
  
env:
  - GOOS=linux CGO=1
  - GOOS=linux CGO=0
  - GOOS=linux GOARCH=arm
  - GOOS=linux GOARCH=mips
  - GOOS=linux GOARCH=mipsle
  - GOOS=windows GOARCH=386